// <auto-generated />
using System;
using AuraPlus.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AuraPlus.Web.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuraPlus.Web.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("NmTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_time");

                    b.HasKey("Id");

                    b.ToTable("t_arp_equipe", (string)null);
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Reconhecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("data")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdReconhecedor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_reconhecedor");

                    b.Property<int>("IdReconhecido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_reconhecido");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("IdReconhecedor");

                    b.HasIndex("IdReconhecido");

                    b.ToTable("t_arp_reconhecimento", (string)null);
                });

            modelBuilder.Entity("AuraPlus.Web.Models.RelatorioEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("data")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descritivo")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descritivo");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_equipe");

                    b.Property<string>("SentimentoMedio")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("sentimento_medio");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipe");

                    b.ToTable("t_arp_relatorio_equipe", (string)null);
                });

            modelBuilder.Entity("AuraPlus.Web.Models.RelatorioPessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("data")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descritivo")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descritivo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.Property<int>("NumeroIndicacoes")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5,0)")
                        .HasDefaultValue(0)
                        .HasColumnName("numero_indicacoes");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_arp_relatorio_pessoa", (string)null);
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Sentimentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("data")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NomeSentimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_sentimento");

                    b.Property<decimal?>("ValorPontuacao")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("valor_pontuacao");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_arp_sentimentos", (string)null);
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasDefaultValue("1")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("cargo");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("data_admissao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("email");

                    b.Property<int?>("IdEquipe")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_equipe");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEquipe");

                    b.ToTable("t_arp_users", (string)null);
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Reconhecimento", b =>
                {
                    b.HasOne("AuraPlus.Web.Models.Users", "Reconhecedor")
                        .WithMany("ReconhecimentosFeitos")
                        .HasForeignKey("IdReconhecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuraPlus.Web.Models.Users", "Reconhecido")
                        .WithMany("ReconhecimentosRecebidos")
                        .HasForeignKey("IdReconhecido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reconhecedor");

                    b.Navigation("Reconhecido");
                });

            modelBuilder.Entity("AuraPlus.Web.Models.RelatorioEquipe", b =>
                {
                    b.HasOne("AuraPlus.Web.Models.Equipe", "Equipe")
                        .WithMany("RelatoriosEquipe")
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("AuraPlus.Web.Models.RelatorioPessoa", b =>
                {
                    b.HasOne("AuraPlus.Web.Models.Users", "Usuario")
                        .WithMany("RelatoriosPessoa")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Sentimentos", b =>
                {
                    b.HasOne("AuraPlus.Web.Models.Users", "Usuario")
                        .WithMany("Sentimentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Users", b =>
                {
                    b.HasOne("AuraPlus.Web.Models.Equipe", "Equipe")
                        .WithMany("Users")
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Equipe", b =>
                {
                    b.Navigation("RelatoriosEquipe");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AuraPlus.Web.Models.Users", b =>
                {
                    b.Navigation("ReconhecimentosFeitos");

                    b.Navigation("ReconhecimentosRecebidos");

                    b.Navigation("RelatoriosPessoa");

                    b.Navigation("Sentimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
